= Development
include::partial$base.adoc[]
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-openwc: https://github.com/open-wc/open-wc
:uri-docs: https://danyill.github.io/tpnz-openscd-docs/subscriber-later-binding
:uri-openscd-core-plugin-demo: https://danyill.github.io/oscd-subscriber-later-binding/index.deploy.html

== License

* This plugin is a web component and follows the  {uri-openwc}[open-wc] recommendations.

* This plugin uses the Apache License and is intended for you to use, study, share and improve.

== Prerequisites

This plugin uses Node.js and the npm package ecosystem and is verified to work on Linux.

For development, you'll need Node.js (including npm, which is bundled with Node.js) on your system.

To check whether you have Node.js installed, and which version, open a terminal and type:

 $ node -v

A good way to install Node.js is to use {uri-nvm}[nvm] (Node Version Manager), however system-wide installations may also work.

If you're using Linux or macOS, follow {uri-nvm-install}[the nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a *new* terminal and install the active Node.js LTS release using:

 $ nvm install --lts

Now that you have Node.js installed, you can install this plugin.

== Cloning and Demo Server

TIP: This repository uses Git LFS so ensure this is installed on your system prior
(on Debian based systems `sudo apt install git-lfs`).
Then clone this repository using:

[subs=+attributes]
$ git clone {url-repo}

Now, install dependencies

 $ npm i

Start up a demo server

 $ npm run start

Now open in your browser locally to http://localhost:8000/demo/ to use the plugin.

== Linting and formatting

To scan the project for linting and formatting errors, run

 $ npm run lint

To automatically fix linting and formatting errors, run

 $ npm run format

== Testing with Web Test Runner

To execute a single test run:

 $ npm run test

To run the tests in interactive watch mode run:

 $ npm run test:watch
