== <oscd-subscriber-later-binding>

This webcomponent follows the
https://github.com/open-wc/open-wc[open-wc] recommendation.

=== What is this?

This is a plugin for
https://github.com/openscd/open-scd-core#readme[open-scd-core], the core
editor engine for OpenSCD.

This plugin is intended to allow a user to carry out later-binding
subscriptions for GOOSE and SMV.

Start up a demo server with `npm start` and see for yourself!

=== Linting and formatting

To scan the project for linting and formatting errors, run

[source,bash]
----
npm run lint
----

To automatically fix linting and formatting errors, run

[source,bash]
----
npm run format
----

=== Testing with Web Test Runner

____
This demo plugin does nothing much that could be tested as it relies
exclusively on built-in browser components to do its job. We therefore
currently have no tests. If you find something that could be tested,
please feel free!
____

To execute a single test run:

[source,bash]
----
npm run test
----

To run the tests in interactive watch mode run:

[source,bash]
----
npm run test:watch
----

=== Tooling configs

For most of the tools, the configuration is in the `package.json` to
reduce the number of files in your project.

If you customize the configuration a lot, you can consider moving them
to individual files.

=== Local Demo with `web-dev-server`

[source,bash]
----
npm start
----

To run a local development server that serves the basic demo located in
`demo/index.html`

© 2023 OpenSCD Daniel Mulholland, Christian Dinkel
