= OpenSCD Plugin: Subscriber Later Binding
:sectnums:
:sectlinks:
:toc: macro
:imagesdir: docs/media
:icons: font
:experimental:
:uri-openwc: https://github.com/open-wc/open-wc
:uri-docs: https://danyill.github.io/tpnz-openscd-docs/subscriber-later-binding
:uri-openscd-core-plugin-demo: https://danyill.github.io/oscd-subscriber-later-binding/index.deploy.html
// badges
image:https://github.com/danyill/oscd-subscriber-later-binding/actions/workflows/test.yml/badge.svg[title='Build Status']
image:https://img.shields.io/badge/built%20with-open--wc-blue.svg[link={uri-openwc},title='Built with open-wc recommendations']
image:https://img.shields.io/badge/Zulip%20-%20%23OpenSCD%20chat-purple?logo=zulip&color=2aa198&labelColor=6c71c4[link=https://openscd.zulipchat.com/]

toc::[]

== What is this?

This plugin is intended to allow a user to carry out later-binding subscriptions for IEC 61850 GOOSE and SMV.

This is a plugin for OpenSCD core, the core editor engine for OpenSCD.



It offers a publisher and subscriber view to allow efficient and intuitive use.

Feel free to log issues to request fixes, improvements or new features.

See the {uri-docs}[documentation] for more information.

== Credit

This plugin was refactored from base code in OpenSCD and relies on the code, architecture and review effort of multiple people other than the authors of this plugin, including:

* Rob Tjalma
* Dennis Labordus
* Juan Munoz

© 2024 OpenSCD Daniel Mulholland, Christian Dinkel, Jakob Vogelsang
